language: python

notifications:
  email: false

python:
- '3.6'
- '3.7'
- '3.8'

before_install:
- pip install python-coveralls
- pip install "pytest-faulthandler>=1.5.0,<2.0.0"
- pip install pytest-cov

install:
- pip install tensorflow==2.0.0
- pip install pytest
- pip install -e .[tests]

script:
- while sleep 10m; do echo "=====[ $SECONDS seconds still running ]====="; done &
- py.test
- kill %1

after_success:
- coveralls